server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8383/realms/demo